
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 27 21:59:22 CEST 2018
//----------------------------------------------------

package com.ctoassembly.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 17;
  public static final int ELSE = 30;
  public static final int SEMICOLON = 22;
  public static final int RELOP = 10;
  public static final int PLUS = 18;
  public static final int RPAREN = 24;
  public static final int LOG_OR = 8;
  public static final int LOG_AND = 7;
  public static final int WHILE = 31;
  public static final int RETURN = 32;
  public static final int INT_NUMBER = 3;
  public static final int AND_OP = 11;
  public static final int IF = 29;
  public static final int SHIFT = 20;
  public static final int RSQBRACKET = 28;
  public static final int LBRACKET = 25;
  public static final int LPAREN = 23;
  public static final int XOR_OP = 13;
  public static final int LSQBRACKET = 27;
  public static final int NOT_OP = 14;
  public static final int ID = 2;
  public static final int RBRACKET = 26;
  public static final int TYPE = 5;
  public static final int STRING = 4;
  public static final int COMMA = 33;
  public static final int INCDEC = 21;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int MINUS = 19;
  public static final int OR_OP = 12;
  public static final int error = 1;
  public static final int ASSIGN = 6;
  public static final int MUL = 15;
  public static final int NOT_LOG_OP = 9;
}

